# Generated by Django 4.2.5 on 2023-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField(max_length=8)),
                ('gamePassword', models.TextField(max_length=12)),
                ('gameAdmin', models.TextField()),
            ],
        ),
    ]
