# Generated by Django 4.2.5 on 2023-11-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='gameID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='gamePassword',
            field=models.TextField(),
        ),
    ]
