# Generated by Django 4.2.5 on 2023-11-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Center', '0006_remove_users_id_alter_users_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Users_In_Game',
        ),
    ]
