# Generated by Django 4.2.5 on 2023-12-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acounts',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Ник')),
                ('password', models.CharField(max_length=1024, verbose_name='Пароль')),
            ],
        ),
    ]
