# Generated by Django 4.2.5 on 2023-12-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acounts',
            new_name='Accounts',
        ),
    ]
