# Generated by Django 4.2.5 on 2023-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0002_rename_acounts_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('number', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Номер')),
                ('password', models.CharField(max_length=1024, null=True, verbose_name='Пароль')),
            ],
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
