# Generated by Django 4.2.5 on 2023-12-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0003_games_delete_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
