# Generated by Django 4.2.5 on 2023-12-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0005_alter_game_number_alter_game_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'игру', 'verbose_name_plural': 'Игры'},
        ),
    ]
