# Generated by Django 4.2.5 on 2023-12-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0009_game_maxplayers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='number',
            new_name='id',
        ),
    ]
