# Generated by Django 4.2.5 on 2023-12-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayFront', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='username',
        ),
    ]
