# Generated by Django 4.2.5 on 2023-12-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayFront', '0003_player_gameid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='gameID',
            new_name='game',
        ),
    ]
