# Generated by Django 4.2.5 on 2023-12-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayFront', '0007_cardfunction_card_descriptin_alter_card_function_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'карту', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterModelOptions(
            name='cardfunction',
            options={'verbose_name': 'функцию карты', 'verbose_name_plural': 'Функции карт'},
        ),
        migrations.AlterField(
            model_name='card',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayFront.cardfunction'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cardfunction',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
