# Generated by Django 4.2.5 on 2023-12-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayFront', '0008_alter_card_options_alter_cardfunction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='card',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayFront.cardfunction', verbose_name='Функция'),
        ),
    ]
