# Generated by Django 4.2.5 on 2023-12-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0006_alter_game_options'),
        ('PlayFront', '0009_card_image_alter_card_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='maxCardInColoda',
            field=models.IntegerField(default=0, verbose_name='Максиьальное число карт в колоде'),
        ),
        migrations.AddField(
            model_name='card',
            name='maxPlayerInGame',
            field=models.IntegerField(default=0, verbose_name='Максиьальное число игрков'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='ColodaX16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.game')),
            ],
        ),
    ]
