# Generated by Django 4.2.5 on 2023-12-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayFront', '0010_card_maxcardincoloda_card_maxplayeringame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCards',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_1', to='PlayFront.card')),
                ('card_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_2', to='PlayFront.card')),
                ('card_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_3', to='PlayFront.card')),
                ('card_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_4', to='PlayFront.card')),
                ('card_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_5', to='PlayFront.card')),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayFront.player')),
            ],
        ),
        migrations.DeleteModel(
            name='ColodaX16',
        ),
    ]
