# Generated by Django 4.2.5 on 2023-12-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0010_rename_number_game_id'),
        ('PlayFront', '0012_coloda_playerplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AddField(
            model_name='player',
            name='gameID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.game'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlayerPlay',
        ),
    ]
