# Generated by Django 4.2.5 on 2023-12-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayFront', '0016_coloda_coloda_coloda_gameid_alter_coloda_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerCards',
        ),
    ]
